travis:
  secure:
    BINSTAR_TOKEN: O0aKPDiSjFG1YdVfJwuDE2P20jtOSzrat5F0vMhUo03B1M7ogC+8RWvlrutN+B0pUdNESCvp6oV+pyXjBvnY5jpX0VoK46VtvGyxBO5hnEs+JgbaOXNLFng4lFYQDYj9eNNqWvbRf2mtcgdnpV/xIYHEs+029jSYR5bN+Qh+9h6oV1/HIH7R4xQdE9x0PudgfyuG+MD4AknzBZLaXFNfqIl7T8x6VlrcjHwV8vMNK9VA7w/YEofXm7e24VR+ZSX4eATVbP+WW5/CXTZvAxQaY0Kd8S90W06WY/AQCkVByUWVz4k1r3kQLN3z2OZH+Ovcjr95Orw4ObGQmcViS4A0xG1ZBgyarOrN8TQ3KJtYTYu/PMb+ULbLmxjtI7Rr0Kyoc4aJnf7EJb9rnucy3WFs7eayGux9z4nmtLry5hi7RIwRFgfA/b+beRLxwIog3GJx443D9ab4GoUkEEh4ws/ZqZpwi8l4DSNmmif2XtOsNH060ojABXFs69xhIykArt8KvkkI6icYQt7RV6mWlBYZdpifHOFrETGPCIkHA1pOQo2ed0WJY4in/ODYZcmIbq872JZsaCiuD+FAVWiQ6M0ufw9s4RWXl5apCzYEnL1t6+mD+e9sOuxYpA3RrVsMolAoHUgk03t9qYgM1WoHKGJwGBfsIWQiQm57PtPFxEl/zxk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
